name: Release

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            glibc: 2.17
            extension: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            glibc: 2.17
            extension: ""

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Rustのpackage名を取得して環境変数に入れておく。(後のステップで使用)
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV

      # zigをインストール
      - name: Install Zig
        uses: mlugg/setup-zig@v1

      # rustをインストール
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.target }}
          bins: cargo-zigbuild

      # moldをインストール
      - uses: rui314/setup-mold@v1

      # ビルド
      - name: Build with glibc version
        if: matrix.glibc != -1
        run: |
          cargo zigbuild --release --target ${{ matrix.target }}.${{ matrix.glibc }}

      - name: Build without glibc version
        if: matrix.glibc == -1
        run: |
          cargo build --release --target ${{ matrix.target }}

      # ビルド済みバイナリをリネーム
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}}

      # ビルド済みバイナリをReleasesに配置
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
